-- Generated by `prisma migrate diff --from-config-datasource --to-schema prisma/schema.prisma --script`.

-- CreateEnum
CREATE TYPE "LeadType" AS ENUM ('CONTACT', 'RESERVATION', 'FRANCHISE', 'BANQUET', 'JOB');

-- CreateEnum
CREATE TYPE "LeadStatus" AS ENUM ('NEW', 'IN_PROGRESS', 'CLOSED');

-- CreateTable
CREATE TABLE "leads" (
    "id" UUID NOT NULL DEFAULT uuidv7(),
    "type" "LeadType" NOT NULL,
    "status" "LeadStatus" NOT NULL DEFAULT 'NEW',
    "name" VARCHAR(180) NOT NULL,
    "phone" VARCHAR(40),
    "email" VARCHAR(320),
    "message" TEXT,
    "payload" JSONB,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "leads_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "leads_type_status_created_at_idx" ON "leads"("type", "status", "created_at");
