import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import type { UpsertMenuCategoryRequest, UpsertMenuItemRequest, UpsertMenuRequest } from '@chashka-coffee/contracts'
import { useMemo, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { useAuth } from '@/features/auth'
import { CatalogAdminApi } from './api'

const menuDraft: UpsertMenuRequest = { slug: '', name: '', description: null }
const categoryDraft: UpsertMenuCategoryRequest = { slug: '', name: '', position: 10 }
const itemDraft: UpsertMenuItemRequest = { slug: '', name: '', description: null, ingredients: null, weightGrams: null, priceKopecks: 0, calories: null, proteins: null, fats: null, carbohydrates: null, isVegetarian: false, isSpicy: false, isLactoseFree: false, isGlutenFree: false, isLight: false, marketingBadge: null, imageUrl: null, position: 10 }

export function MenuPage() {
  const { api: auth } = useAuth(); const api = useMemo(() => new CatalogAdminApi(auth), [auth]); const qc = useQueryClient()
  const [menu, setMenu] = useState(menuDraft); const [category, setCategory] = useState(categoryDraft); const [item, setItem] = useState(itemDraft); const [categoryId, setCategoryId] = useState('')
  const menus = useQuery({ queryKey: ['admin','menus'], queryFn: () => api.listMenus() }); const [selectedId,setSelectedId]=useState<string>('')
  const detail = useQuery({ queryKey:['admin','menu',selectedId], enabled:Boolean(selectedId), queryFn:()=>api.getMenu(selectedId) })
  const refresh=()=>{void qc.invalidateQueries({queryKey:['admin','menus']});void qc.invalidateQueries({queryKey:['admin','menu',selectedId]})}
  const addMenu=useMutation({mutationFn:()=>api.createMenu(menu),onSuccess:(r)=>{setSelectedId(r.menu.id);setMenu(menuDraft);refresh()}})
  const addCategory=useMutation({mutationFn:()=>api.createCategory(selectedId,category),onSuccess:()=>{setCategory(categoryDraft);refresh()}})
  const addItem=useMutation({mutationFn:()=>api.createItem(categoryId,item),onSuccess:()=>{setItem(itemDraft);refresh()}})
  return <section className="mx-auto grid w-full max-w-7xl gap-6 px-5 py-9 lg:grid-cols-[320px_1fr]"><Card><CardHeader><CardTitle>Наборы меню</CardTitle><CardDescription>Один набор может быть назначен нескольким точкам.</CardDescription></CardHeader><CardContent className="grid gap-2">{menus.data?.menus.map(m=><button type="button" key={m.id} onClick={()=>setSelectedId(m.id)} className="rounded-xl border p-3 text-left hover:bg-muted"><b>{m.name}</b><small className="block text-muted-foreground">{m.categoryCount} категорий · {m.restaurantCount} точек</small></button>)}<form className="mt-4 grid gap-2" onSubmit={e=>{e.preventDefault();addMenu.mutate()}}><Input required placeholder="Название нового меню" value={menu.name} onChange={e=>setMenu(v=>({...v,name:e.target.value}))}/><Input required placeholder="city-core" value={menu.slug} onChange={e=>setMenu(v=>({...v,slug:e.target.value}))}/><Button type="submit" disabled={addMenu.isPending}>Создать набор</Button></form></CardContent></Card><div className="grid gap-6">{detail.data ? <><Card><CardHeader><CardTitle>{detail.data.menu.name}</CardTitle><CardDescription>{detail.data.categories.length} категорий. Добавляйте структуру сверху вниз.</CardDescription></CardHeader><CardContent className="grid gap-4">{detail.data.categories.map(c=><div key={c.id} className="border-t pt-4"><div className="flex justify-between"><b>{c.position}. {c.name}</b><Button size="xs" type="button" onClick={()=>setCategoryId(c.id)}>Добавить блюдо</Button></div>{c.items.map(i=><p key={i.id} className="mt-2 text-sm">{i.name} · {i.priceKopecks/100} ₽</p>)}</div>)}</CardContent></Card><div className="grid gap-6 md:grid-cols-2"><Editor title="Новая категория" onSubmit={()=>addCategory.mutate()} disabled={!selectedId||addCategory.isPending}><Input required placeholder="Завтраки" value={category.name} onChange={e=>setCategory(v=>({...v,name:e.target.value}))}/><Input required placeholder="breakfast" value={category.slug} onChange={e=>setCategory(v=>({...v,slug:e.target.value}))}/></Editor><Editor title="Новое блюдо" onSubmit={()=>addItem.mutate()} disabled={!categoryId||addItem.isPending}><Input required placeholder="Название" value={item.name} onChange={e=>setItem(v=>({...v,name:e.target.value}))}/><Input required placeholder="avocado-toast" value={item.slug} onChange={e=>setItem(v=>({...v,slug:e.target.value}))}/><Input required type="number" placeholder="Цена в рублях" value={item.priceKopecks/100} onChange={e=>setItem(v=>({...v,priceKopecks:Number(e.target.value)*100}))}/><p className="text-xs text-muted-foreground">{categoryId ? 'Блюдо добавится в выбранную категорию.' : 'Сначала нажмите «Добавить блюдо» у нужной категории.'}</p></Editor></div></> : <Card><CardContent className="py-14 text-muted-foreground">Выберите набор меню слева.</CardContent></Card>}</div></section>
}
function Editor({title,onSubmit,disabled,children}:{title:string;onSubmit:()=>void;disabled:boolean;children:React.ReactNode}){return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent><form className="grid gap-3" onSubmit={e=>{e.preventDefault();onSubmit()}}>{children}<Button type="submit" disabled={disabled}>Сохранить</Button></form></CardContent></Card>}
