import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { productListResponseSchema, productResponseSchema, upsertProductRequestSchema, type Product, type ProductType, type UpsertProductRequest } from '@chashka-coffee/contracts'
import { useState } from 'react'

import { AdminPageHeader, AdminTabs } from '@/components/admin'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { useAuth } from '@/features/auth'

const nullable = (value: string) => value.trim() || null
const empty = (type: ProductType): UpsertProductRequest => ({ type, status: 'DRAFT', slug: '', name: '', subtitle: null, description: null, ingredients: null, origin: null, roastLevel: null, tastingNotes: [], imageUrl: null, galleryUrls: [], details: [], isFeatured: false, position: 10, variants: [{ label: type === 'COFFEE' ? '250 г' : '1 кг', weightGrams: type === 'COFFEE' ? 250 : 1000, priceKopecks: 0, position: 10, isAvailable: true }] })

export function ProductsPage() {
  const { api } = useAuth(); const queryClient = useQueryClient()
  const [type, setType] = useState<ProductType>('COFFEE'); const [selected, setSelected] = useState<Product | null>(null); const [draft, setDraft] = useState<UpsertProductRequest>(empty('COFFEE'))
  const products = useQuery({ queryKey: ['admin', 'products', type], queryFn: () => api.request(`/api/admin/products?type=${type}`, productListResponseSchema) })
  const save = useMutation({ mutationFn: () => api.request(selected ? `/api/admin/products/${selected.id}` : '/api/admin/products', productResponseSchema, { method: selected ? 'PUT' : 'POST', body: upsertProductRequestSchema.parse(draft) }), onSuccess: ({ product }) => { setSelected(product); setDraft(toDraft(product)); void queryClient.invalidateQueries({ queryKey: ['admin', 'products', type] }) } })
  const start = (next: ProductType) => { setType(next); setSelected(null); setDraft(empty(next)) }
  const change = <K extends keyof UpsertProductRequest>(key: K, value: UpsertProductRequest[K]) => setDraft((current) => ({ ...current, [key]: value }))
  return <section className="admin-page admin-content-workspace">
    <AdminPageHeader eyebrow="Витрина" title="Кофе и кондитерская" description="Отдельный каталог товаров с вариантами веса, ценой, вкусом и подробной страницей." actions={<Button onClick={() => start(type)}>Новый товар</Button>} />
    <AdminTabs label="Тип товара" value={type} onChange={start} tabs={[{ value: 'COFFEE', label: 'Кофе' }, { value: 'CAKE', label: 'Торты' }]} />
    <div className="grid gap-6 lg:grid-cols-[minmax(16rem,.6fr)_minmax(0,1.4fr)]">
      <Card className="admin-resource-list"><CardHeader><CardTitle>{type === 'COFFEE' ? 'Кофе' : 'Торты'}</CardTitle><CardDescription>Выберите товар для редактирования.</CardDescription></CardHeader><CardContent className="grid gap-2">{products.data?.products.map((product) => <button className="admin-list-row" data-selected={selected?.id === product.id || undefined} key={product.id} type="button" onClick={() => { setSelected(product); setDraft(toDraft(product)) }}><span><b>{product.name}</b><small>{product.status === 'PUBLISHED' ? 'Опубликован' : product.status === 'DRAFT' ? 'Черновик' : 'Архив'} · {product.variants.length} вар.</small></span></button>)}{products.isPending ? <p className="text-sm text-muted-foreground">Загружаем товары…</p> : null}{products.isError ? <p className="text-sm text-destructive">Не удалось загрузить каталог.</p> : null}</CardContent></Card>
      <Card className="admin-editor-card"><CardHeader><CardTitle>{selected ? selected.name : 'Новый товар'}</CardTitle><CardDescription>Поля ниже формируют карточку и подробную страницу товара.</CardDescription></CardHeader><CardContent><form className="grid gap-5" onSubmit={(event) => { event.preventDefault(); save.mutate() }}>
        <div className="grid gap-4 sm:grid-cols-3"><Field label="Тип"><select value={draft.type} onChange={(event) => change('type', event.target.value as ProductType)}><option value="COFFEE">Кофе</option><option value="CAKE">Торт</option></select></Field><Field label="Статус"><select value={draft.status} onChange={(event) => change('status', event.target.value as UpsertProductRequest['status'])}><option value="DRAFT">Черновик</option><option value="PUBLISHED">Опубликован</option><option value="ARCHIVED">Архив</option></select></Field><Field label="Порядок"><Input min={0} type="number" value={draft.position} onChange={(event) => change('position', Number(event.target.value))} /></Field></div>
        <div className="grid gap-4 sm:grid-cols-2"><Field label="Название"><Input required value={draft.name} onChange={(event) => change('name', event.target.value)} /></Field><Field label="Адрес страницы"><Input required placeholder="ethiopia-guji" value={draft.slug} onChange={(event) => change('slug', event.target.value)} /></Field></div>
        <Field label="Подзаголовок"><Input value={draft.subtitle ?? ''} onChange={(event) => change('subtitle', nullable(event.target.value))} /></Field>
        <Field label="Описание"><Textarea className="min-h-28" value={draft.description ?? ''} onChange={(event) => change('description', nullable(event.target.value))} /></Field>
        <div className="grid gap-4 sm:grid-cols-2"><Field label="Состав"><Textarea value={draft.ingredients ?? ''} onChange={(event) => change('ingredients', nullable(event.target.value))} /></Field><Field label="Основное изображение"><Input value={draft.imageUrl ?? ''} onChange={(event) => change('imageUrl', nullable(event.target.value))} /></Field></div>
        {draft.type === 'COFFEE' ? <div className="grid gap-4 sm:grid-cols-2"><Field label="Происхождение"><Input value={draft.origin ?? ''} onChange={(event) => change('origin', nullable(event.target.value))} /></Field><Field label="Обжарка"><Input value={draft.roastLevel ?? ''} onChange={(event) => change('roastLevel', nullable(event.target.value))} /></Field></div> : null}
        <div className="grid gap-4 sm:grid-cols-2"><Field label="Вкусовые ноты (через запятую)"><Input value={draft.tastingNotes.join(', ')} onChange={(event) => change('tastingNotes', event.target.value.split(',').map((value) => value.trim()).filter(Boolean))} /></Field><Field label="Галерея (по одному URL в строке)"><Textarea value={draft.galleryUrls.join('\n')} onChange={(event) => change('galleryUrls', event.target.value.split('\n').map((value) => value.trim()).filter(Boolean))} /></Field></div>
        <Field label="Характеристики (Название | Значение — по одной в строке)"><Textarea value={draft.details.map((item) => `${item.label} | ${item.value}`).join('\n')} onChange={(event) => change('details', event.target.value.split('\n').filter(Boolean).map((line) => { const [label = '', value = ''] = line.split('|').map((part) => part.trim()); return { label, value } }))} /></Field>
        <section className="admin-variant-editor"><header><div><strong>Варианты и цены</strong><p>Например, 250 г и 1 кг для кофе или конкретный вес торта.</p></div><Button type="button" variant="outline" onClick={() => change('variants', [...draft.variants, { label: 'Новый вариант', weightGrams: null, priceKopecks: 0, position: (draft.variants.length + 1) * 10, isAvailable: true }])}>Добавить вариант</Button></header>{draft.variants.map((variant, index) => <div className="admin-variant-row" key={`${index}-${variant.position}`}><Input aria-label="Название варианта" value={variant.label} onChange={(event) => change('variants', draft.variants.map((item, itemIndex) => itemIndex === index ? { ...item, label: event.target.value } : item))} /><Input aria-label="Вес, г" min={1} placeholder="Вес, г" type="number" value={variant.weightGrams ?? ''} onChange={(event) => change('variants', draft.variants.map((item, itemIndex) => itemIndex === index ? { ...item, weightGrams: event.target.value ? Number(event.target.value) : null } : item))} /><Input aria-label="Цена, ₽" min={0} placeholder="Цена, ₽" type="number" value={variant.priceKopecks / 100} onChange={(event) => change('variants', draft.variants.map((item, itemIndex) => itemIndex === index ? { ...item, priceKopecks: Number(event.target.value) * 100 } : item))} /><label><input checked={variant.isAvailable} type="checkbox" onChange={(event) => change('variants', draft.variants.map((item, itemIndex) => itemIndex === index ? { ...item, isAvailable: event.target.checked } : item))} /> В продаже</label><Button disabled={draft.variants.length === 1} type="button" variant="ghost" onClick={() => change('variants', draft.variants.filter((_, itemIndex) => itemIndex !== index))}>Удалить</Button></div>)}</section>
        <label className="flex items-center gap-2 text-sm font-medium"><input checked={draft.isFeatured} type="checkbox" onChange={(event) => change('isFeatured', event.target.checked)} />Показывать в избранных</label>
        {save.isError ? <p className="text-sm text-destructive">Не удалось сохранить. Проверьте адрес страницы, изображения и цены.</p> : null}<Button disabled={save.isPending} size="lg" type="submit">{save.isPending ? 'Сохраняем…' : 'Сохранить товар'}</Button>
      </form></CardContent></Card>
    </div>
  </section>
}

function toDraft(product: Product): UpsertProductRequest { const { id: _id, createdAt: _createdAt, updatedAt: _updatedAt, variants, ...rest } = product; return { ...rest, variants: variants.map(({ id: _variantId, ...variant }) => variant) } }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-sm font-medium">{label}{children}</label> }
