import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { jobOpeningListResponseSchema, jobOpeningResponseSchema, upsertJobOpeningRequestSchema, type JobOpening, type UpsertJobOpeningRequest } from '@chashka-coffee/contracts'
import { useState } from 'react'

import { AdminPageHeader } from '@/components/admin'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { useAuth } from '@/features/auth'

const empty: UpsertJobOpeningRequest = { slug: '', title: '', department: null, location: 'Новосибирск', employmentType: null, description: null, isPublished: false, position: 10 }
const nullable = (value: string) => value.trim() || null
const toDraft = (opening: JobOpening): UpsertJobOpeningRequest => { const { id: _id, createdAt: _createdAt, updatedAt: _updatedAt, ...draft } = opening; return draft }

export function JobsPage() {
  const { api } = useAuth(); const queryClient = useQueryClient(); const [selected, setSelected] = useState<JobOpening | null>(null); const [draft, setDraft] = useState(empty)
  const openings = useQuery({ queryKey: ['admin', 'jobs'], queryFn: () => api.request('/api/admin/jobs', jobOpeningListResponseSchema) })
  const save = useMutation({ mutationFn: () => selected ? api.request(`/api/admin/jobs/${selected.id}`, jobOpeningResponseSchema, { method: 'PUT', body: upsertJobOpeningRequestSchema.parse(draft) }) : api.request('/api/admin/jobs', jobOpeningResponseSchema, { method: 'POST', body: upsertJobOpeningRequestSchema.parse(draft) }), onSuccess: ({ opening }) => { setSelected(opening); setDraft(toDraft(opening)); void queryClient.invalidateQueries({ queryKey: ['admin', 'jobs'] }) } })
  const change = <K extends keyof UpsertJobOpeningRequest>(key: K, value: UpsertJobOpeningRequest[K]) => setDraft((current) => ({ ...current, [key]: value }))
  return <section className="admin-page">
    <AdminPageHeader eyebrow="Публикация" title="Вакансии" description="Позиции, которые посетители видят на сайте и по которым могут оставить отклик." actions={<Button type="button" onClick={() => { setSelected(null); setDraft(empty) }}>Новая вакансия</Button>} />
    <div className="grid gap-6 lg:grid-cols-[minmax(16rem,.62fr)_minmax(0,1.38fr)]"><Card className="admin-resource-list"><CardHeader><CardTitle>Все вакансии</CardTitle><CardDescription>Выберите позицию для редактирования.</CardDescription></CardHeader><CardContent className="grid gap-2">{openings.isPending ? <p className="text-sm text-muted-foreground">Загружаем вакансии…</p> : null}{openings.data?.openings.map((opening) => <button className="admin-list-row" data-selected={selected?.id === opening.id || undefined} key={opening.id} onClick={() => { setSelected(opening); setDraft(toDraft(opening)) }} type="button"><span><b>{opening.title}</b><small>{opening.isPublished ? 'Опубликована' : 'Черновик'}</small></span></button>)}{openings.isError && <p className="text-sm text-destructive">Не удалось загрузить вакансии.</p>}</CardContent></Card><Card className="admin-editor-card"><CardHeader><CardTitle>{selected ? 'Редактирование вакансии' : 'Новая вакансия'}</CardTitle><CardDescription>Опубликуйте позицию, когда она готова к приёму откликов.</CardDescription></CardHeader><CardContent><form className="grid gap-4" onSubmit={(event) => { event.preventDefault(); save.mutate() }}><Field label="Название"><Input required value={draft.title} onChange={(event) => change('title', event.target.value)} /></Field><Field label="Адрес страницы"><Input required placeholder="barista" value={draft.slug} onChange={(event) => change('slug', event.target.value)} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Направление"><Input value={draft.department ?? ''} onChange={(event) => change('department', nullable(event.target.value))} /></Field><Field label="Локация"><Input value={draft.location ?? ''} onChange={(event) => change('location', nullable(event.target.value))} /></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Тип занятости"><Input placeholder="Полная занятость" value={draft.employmentType ?? ''} onChange={(event) => change('employmentType', nullable(event.target.value))} /></Field><Field label="Порядок"><Input min={0} type="number" value={draft.position} onChange={(event) => change('position', Number(event.target.value))} /></Field></div><Field label="Описание"><Textarea className="min-h-40" value={draft.description ?? ''} onChange={(event) => change('description', nullable(event.target.value))} /></Field><label className="flex items-center gap-2 text-sm font-medium"><input checked={draft.isPublished} type="checkbox" onChange={(event) => change('isPublished', event.target.checked)} />Опубликовать на сайте</label>{save.isError && <p className="text-sm text-destructive">Не удалось сохранить вакансию. Проверьте адрес страницы.</p>}<Button disabled={save.isPending} size="lg" type="submit">{save.isPending ? 'Сохраняем…' : 'Сохранить'}</Button></form></CardContent></Card></div>
  </section>
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-sm font-medium">{label}{children}</label> }
