-- Generated by `prisma migrate diff --from-config-datasource --to-schema prisma/schema.prisma --script`.

-- CreateTable
CREATE TABLE "job_openings" (
    "id" UUID NOT NULL DEFAULT uuidv7(),
    "slug" VARCHAR(120) NOT NULL,
    "title" VARCHAR(180) NOT NULL,
    "department" VARCHAR(120),
    "location" VARCHAR(180),
    "employment_type" VARCHAR(80),
    "description" TEXT,
    "is_published" BOOLEAN NOT NULL DEFAULT false,
    "position" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "job_openings_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "job_openings_slug_key" ON "job_openings"("slug");

-- CreateIndex
CREATE INDEX "job_openings_published_position_idx" ON "job_openings"("is_published", "position");
