-- Generated by `prisma migrate diff --from-config-datasource --to-schema prisma/schema.prisma --script`.

-- CreateEnum
CREATE TYPE "MediaAssetStatus" AS ENUM ('PENDING', 'READY');

-- AlterTable
ALTER TABLE "media_assets" ADD COLUMN "status" "MediaAssetStatus" NOT NULL DEFAULT 'READY';
