-- This migration was generated by `prisma migrate diff` after `prisma migrate dev`
-- could not initialize its schema engine against the local PostgreSQL 18 image.
CREATE TYPE "ContentEntryType" AS ENUM ('PROMOTION', 'EVENT');

CREATE TYPE "PublicationStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED');

CREATE TABLE "content_entries" (
    "id" UUID NOT NULL DEFAULT uuidv7(),
    "type" "ContentEntryType" NOT NULL,
    "status" "PublicationStatus" NOT NULL DEFAULT 'DRAFT',
    "slug" VARCHAR(120) NOT NULL,
    "title" VARCHAR(180) NOT NULL,
    "excerpt" VARCHAR(500),
    "body" TEXT,
    "image_url" TEXT,
    "cta_label" VARCHAR(80),
    "cta_url" TEXT,
    "starts_at" TIMESTAMP(3),
    "ends_at" TIMESTAMP(3),
    "event_starts_at" TIMESTAMP(3),
    "location" VARCHAR(220),
    "is_featured" BOOLEAN NOT NULL DEFAULT false,
    "position" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "content_entries_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "content_entries_slug_key" ON "content_entries"("slug");
CREATE INDEX "content_entries_type_status_position_idx" ON "content_entries"("type", "status", "position");
CREATE INDEX "content_entries_starts_at_idx" ON "content_entries"("starts_at");
